package com.mnb.manobacademy.ui.theme // Sesuaikan package jika berbeda

import androidx.compose.ui.graphics.Color

// Light Colors (Asumsi sudah benar)
val primaryLight = Color(0xFF0A6780)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB9EAFF)
val onPrimaryContainerLight = Color(0xFF001F29)
val secondaryLight = Color(0xFF4C626B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCFE6F1)
val onSecondaryContainerLight = Color(0xFF071E26)
val tertiaryLight = Color(0xFF5B5B7E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE1E0FF)
val onTertiaryContainerLight = Color(0xFF181837)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FAFD)
val onBackgroundLight = Color(0xFF171C1F)
val surfaceLight = Color(0xFFF5FAFD)
val onSurfaceLight = Color(0xFF171C1F)
val surfaceVariantLight = Color(0xFFDCE4E8)
val onSurfaceVariantLight = Color(0xFF40484C)
val outlineLight = Color(0xFF70787C)
val outlineVariantLight = Color(0xFFC0C8CC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3134)
val inverseOnSurfaceLight = Color(0xFFEDF1F4)
val inversePrimaryLight = Color(0xFF89D0ED)
val surfaceDimLight = Color(0xFFD6DBDE)
val surfaceBrightLight = Color(0xFFF5FAFD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F4F7)
val surfaceContainerLight = Color(0xFFEAEEF2)
val surfaceContainerHighLight = Color(0xFFE4E9EC)
val surfaceContainerHighestLight = Color(0xFFDEE3E6)

// --- WARNA GELAP LENGKAP ---
val primaryDark = Color(0xFF89D0ED)
val onPrimaryDark = Color(0xFF003544)
val primaryContainerDark = Color(0xFF004D61)
val onPrimaryContainerDark = Color(0xFFB9EAFF)
val secondaryDark = Color(0xFFB3CAD5)
val onSecondaryDark = Color(0xFF1E333C) // <<< INI YANG HILANG SEBELUMNYA
val secondaryContainerDark = Color(0xFF354A53)
val onSecondaryContainerDark = Color(0xFFCFE6F1)
val tertiaryDark = Color(0xFFC4C3EB)
val onTertiaryDark = Color(0xFF2D2D4D)
val tertiaryContainerDark = Color(0xFF434465)
val onTertiaryContainerDark = Color(0xFFE1E0FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1416)
val onBackgroundDark = Color(0xFFDEE3E6)
val surfaceDark = Color(0xFF0F1416)
val onSurfaceDark = Color(0xFFDEE3E6)
val surfaceVariantDark = Color(0xFF40484C)
val onSurfaceVariantDark = Color(0xFFC0C8CC)
val outlineDark = Color(0xFF8A9296)
val outlineVariantDark = Color(0xFF40484C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E6)
val inverseOnSurfaceDark = Color(0xFF2C3134)
val inversePrimaryDark = Color(0xFF0A6780)
val surfaceDimDark = Color(0xFF0F1416)
val surfaceBrightDark = Color(0xFF353A3D)
val surfaceContainerLowestDark = Color(0xFF0A0F11)
val surfaceContainerLowDark = Color(0xFF171C1F)
val surfaceContainerDark = Color(0xFF1B2023)
val surfaceContainerHighDark = Color(0xFF252B2D)
val surfaceContainerHighestDark = Color(0xFF303638)


// --- WARNA KONTRAST (Asumsi sudah benar atau tidak digunakan jika error hanya onSecondaryDark) ---
// Light Medium Contrast Colors
val primaryLightMediumContrast = Color(0xFF00495C)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF307D97)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
// ... (Lengkapi jika perlu)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDEE3E6)

// Light High Contrast Colors
val primaryLightHighContrast = Color(0xFF002631)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF00495C)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
// ... (Lengkapi jika perlu)
val surfaceContainerHighestLightHighContrast = Color(0xFFDEE3E6)

// Dark Medium Contrast Colors
val primaryDarkMediumContrast = Color(0xFF8DD5F1)
val onPrimaryDarkMediumContrast = Color(0xFF001922)
val primaryContainerDarkMediumContrast = Color(0xFF519AB5)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
// ... (Lengkapi jika perlu)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF303638)

// Dark High Contrast Colors
val primaryDarkHighContrast = Color(0xFFF6FBFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF8DD5F1)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
// ... (Lengkapi jika perlu)
val surfaceContainerHighestDarkHighContrast = Color(0xFF303638)
